### PR TITLE
Update to 7.1

### LINKED ISSUE #27: Incorrect name in macOS menubar
The name in the macOS menubar is not "MNELAB" but "python". Furthermore, all names inside this menu are "__main__.py" instead of MNELAB.
Screen Shot 2020-12-23 at 13 28 25
@hoechenberger any idea what could be wrong? `pyobjc-framework-cocoa` is installed.

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes https://github.com/conda-forge/mnelab-feedstock/issues/27.

* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@jschueller this should fix the failing automatic builds.

### CODE REVIEW

**Comment by cbrnr** [comment]
@conda-forge-admin, please rerender

**Comment by hoechenberger** [comment]
@cbrnr in `meta.yaml`, can you please update the `run` dependency from
```
    - pyobjc-core
```
to
```
    - pyobjc-core >=7.1
```
?

**Comment by hoechenberger** [comment]
@jschueller Can you have a look / merge this once @cbrnr has updated the dependencies? Thanks!

**Comment by cbrnr** [comment]
Thanks @hoechenberger. @jschueller ready to merge.

**Comment by hoechenberger** [comment]
Thank you for your swift action, @jschueller!

**Pull request merged**
